Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using LexiconLMS.Models;
using Microsoft.AspNetCore.Authorization;
using LexiconLMS.Data;
using LexiconLMS.Core.Models;
using Microsoft.AspNetCore.Identity;
using LexiconLMS.Core.Services;
using LexiconLMS.Core.ViewModels;

namespace LexiconLMS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<SystemUser> _userManager;
        private readonly IUserService _userService;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context, UserManager<SystemUser> userManager, IUserService userService)
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;
            _userService = userService;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            SystemUser systemUser = await _userManager.GetUserAsync(User);
            return View(await _userService.GetUserMainViewModel(systemUser.Id));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = System.Diagnostics.Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult ModuleDetails(int id)
        {
            return ViewComponent("ModuleDetails", new { moduleId = id });
        }
        public IActionResult ActivityDetails(int id)
        {
            return ViewComponent("ActivityDetails", new { activityId = id });
        }
    }
}

Core/ViewComponents/CourseViewComponent.cs
using LexiconLMS.Core.Models;
using LexiconLMS.Core.Repository;
using LexiconLMS.Data;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace LexiconLMS.Core.ViewComponents
{
    public class CourseViewComponent : ViewComponent
    {
        private ApplicationDbContext _context { get; }
        private ICourseRepository _courseRepository { get; }
        public CourseViewComponent(ApplicationDbContext context, ICourseRepository courseRepository)
        {
            _context = context;
            _courseRepository = courseRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(Course course)
        {
            return View(course);
        }
    }
}

Core/ViewComponents/ModulesViewComponent.cs
using LexiconLMS.Core.Repository;
using LexiconLMS.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LexiconLMS.Core.ViewComponents
{
    public class ModulesViewComponent : ViewComponent
    {
        private ApplicationDbContext _context { get; }
        private ICourseRepository _courseRepository { get; }
        public ModulesViewComponent(ApplicationDbContext context, ICourseRepository courseRepository)
        {
            _context = context;
            _courseRepository = courseRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(int courseId)
        {
            return View(await _courseRepository.GetAllCourseModulesAsync(courseId));
        }
    }
}

Core/ViewComponents/SystemUser/GetUsersNotInCourseViewComponent.cs
using LexiconLMS.Core.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LexiconLMS.Core.ViewComponents.SystemUser
{
    public class GetUsersNotInCourseViewComponent : ViewComponent
    {
        private readonly IUserService _userService;

        public GetUsersNotInCourseViewComponent(IUserService userService)
        {
            _userService = userService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int courseId, bool mainPage)
        {
            if (mainPage)
            {
                return View(await _userService.GetSystemUsersNotInCourse(courseId));

            }
            return View("StandardEdit", await _userService.GetSystemUsersNotInCourse(courseId));
        }
    }
}

Core/ViewComponents/UsersViewComponent.cs
using LexiconLMS.Core.Services;
using LexiconLMS.Data;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace LexiconLMS.Core.ViewComponents
{
    public class UsersViewComponent : ViewComponent
    {
        private ApplicationDbContext _context { get; }
        private IUserService _userService { get; }

        public UsersViewComponent(ApplicationDbContext context, IUserService userService)
        {
            _context = context;
            _userService = userService;
        }
        public async Task<IViewComponentResult> InvokeAsync(int courseId)
        {
            //TODO Make get Parvin's function for getting users in a course.
            return View(_userService.GetSystemUserViewModels(courseId));
        }
    }
}

Views/Home/Index.cshtml
@model LexiconLMS.Core.ViewModels.MainViewModel

@{
    ViewData["Title"] = "Home Page";
}

@if (Model.Course != null)
{
    <div class="row text-center" id="mainbackgroundcolor">
        <div class="col-md-12">
            <h2>
                <a asp-controller="Home" asp-action="Index" style="color: black;">
                    @Model.Course.Name
                </a>
            </h2>
        </div>
    </div>

    <div class="row" id="mainbackgroundcolor">
        <div class="col-md-2" id="mainmoduleactivityelement" style="height: 68vh; overflow:auto;">
            @await Component.InvokeAsync("Modules", new { courseId = Model.Course.Id })
        </div>
        <div class="col-md-8" id="maincourseelement" style="height: 68vh; overflow:auto;">
            @await Component.InvokeAsync("Course", new { course = Model.Course })
        </div>
        <div class="col-md-2" id="mainsystemuserselement">
            <h5 class="text-center">Students</h5>
            <hr />
            <button type="button" id="systemUsersPopUp" class="btn btn-primary btn-sm" style="width: 100%" data-toggle="modal" data-target="systemUsersMainModalCenter">Add Member</button>
            <br />
            <!--SystemUser Modal-->
            <div class="modal fade" id="systemUsersMainModalCenter" tabindex="-1" role="dialog" aria-labelledby="systemUsersModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h3 class="modal-title" id="exampleModalLongTitle">Add Members to the course</h3>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="usermodalbody">
                            @await Component.InvokeAsync("GetUsersNotInCourse", new { courseId = Model.Course.Id, mainPage = true })
                        </div>
                    </div>
                </div>
            </div>
            <div id="usercourselist">
                @await Component.InvokeAsync("Users", new { courseId = Model.Course.Id })
            </div>
        </div>
    </div>
}
else
{
    <h1>No course</h1>
    <p>This user is not registered on a course.</p>
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">

</script>

<script type="text/javascript">

    $("#modulePopUp").click(function () {
        $("#moduleModalCenter").modal('show');
    });

    $("#btnHideModal").click(function () {
        $("#moduleModalCenter").modal('hide');
    });
    $("#systemUsersPopUp").click(function () {
        $("#systemUsersMainModalCenter").modal('show');
    });
</script>