Areas/Identity/Pages/Account/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using LexiconLMS.Core.Models;
using LexiconLMS.Data;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;

namespace LexiconLMS.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class RegisterModel : PageModel
    {
        private readonly SignInManager<SystemUser> _signInManager;
        private readonly UserManager<SystemUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ILogger<RegisterModel> _logger;

        public RegisterModel(
            UserManager<SystemUser> userManager,
            SignInManager<SystemUser> signInManager,
            ILogger<RegisterModel> logger,
            RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _roleManager = roleManager;
            Roles = _roleManager.Roles.Select(x => x.Name).ToList();
        }

        [BindProperty]
        public InputModel Input { get; set; }
        [Required]
        public List<string> Roles;

        public string ReturnUrl { get; set; }

        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        public class InputModel
        {
            [Required]
            public string Role { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 4)]
            [Display(Name = "Name")]
            public string Name { get; set; }

            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            ReturnUrl = returnUrl;
            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
            if (ModelState.IsValid)
            {
                var user = new SystemUser 
                { 
                    Name = Input.Name,
                    UserName = Input.Email, 
                    Email = Input.Email
                };
                var result = await _userManager.CreateAsync(user, Input.Password);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User created a new account with password.");

                    var resultAddRole = await _userManager.AddToRoleAsync(user, Input.Role);

                    /* INCASE WE NEED CONFIRMATIONS AGAIN
                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                    var callbackUrl = Url.Page(
                        "/Account/ConfirmEmail",
                        pageHandler: null,
                        values: new { area = "Identity", userId = user.Id, code = code },
                        protocol: Request.Scheme);

                    await _emailSender.SendEmailAsync(Input.Email, "Confirm your email",
                        $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");
                    */

                    return RedirectToAction("Index", "SystemUser");
                    /* INCASE WE NEED IT AGAIN
                    if (_userManager.Options.SignIn.RequireConfirmedAccount)
                    {
                        return RedirectToPage("RegisterConfirmation", new { email = Input.Email });
                    }
                    else
                    {
                        await _signInManager.SignInAsync(user, isPersistent: false);
                        return LocalRedirect(returnUrl);
                    }
                    */
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using LexiconLMS.Core.Services;
using LexiconLMS.Core.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace LexiconLMS.Controllers
{
    [Authorize]
    public class DocumentController : Controller
    {
        private IDocumentService _documentService;
        public DocumentController(IDocumentService documentService)
        {
            _documentService = documentService;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> ActivityDocumentUpload(ActivityDocumentUploadViewModel model)
        {
            if (model.FormFile==null)
            {
                return RedirectToAction("Error", "Home");

            }

            var success = await _documentService.SaveActivityDocumentToFile(model);
            if (success)
                return RedirectToAction(@"Details", "Activity", new { Id = model.ActivityId });
            else
                return RedirectToAction("Error", "Home");
        }



        public async Task<IActionResult> CourseDocumentUpload(CourseDocumentUploadViewModel model)
        {
            if (model.FormFile == null)
            {
                return RedirectToAction("Error", "Home");

            }

            //var success = await _documentService.SaveCourseDocumentToFile(model.FormFile,model.UserId,model.CourseId);
            var success = await _documentService.SaveCourseDocumentToFile(model);
            if (success)
                return RedirectToAction(@"Details", "Courses", new { Id = model.CourseId });
            else
                return RedirectToAction("Error", "Home");
        }




        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> AssignmentDocumentUpload(AssignmentDocumentUploadViewModel model)
        {
            var success = await _documentService.SaveAssignmentDocumentToFile(model);
            if (success)
                return RedirectToAction(@"Details", "Activity", new { Id = model.ActivityId });
            else
                return RedirectToAction("Error", "Home");
        }

        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> ModuleDocumentUpload(ModuleDocumentUploadViewModel model)
        {
            var success = await _documentService.SaveModuleDocumentToFile(model);
            if (success)
                return RedirectToAction(@"Details", "Module", new { Id = model.ModuleId });
            else
                return RedirectToAction("Error", "Home");
        }

        [HttpGet]
        public IActionResult UploadUserDocument(string userId)
        {
            return View(new UserDocumentUploadViewModel { UserId = userId });
        }

        [HttpGet]
        public async Task<IActionResult> DownloadDocument(int documentId)
        {
            var document = await _documentService.GetDocumentByIdAsync(documentId);
            if (document != null)
            {
                using (FileStream stream = new FileStream(document.Path, FileMode.Open))
                {
                    var memory = new MemoryStream();
                    await stream.CopyToAsync(memory);
                    memory.Position = 0;
                    var ext = Path.GetExtension(document.Name).ToLowerInvariant();
                    return File(memory, GetMimeTypes()[ext], document.Name);
                }
            }
            else
            {
                return NotFound();
            }
        }

        // Keeps track of some common expected file types.
        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
            {
                {".txt", "text/plain"},
                {".pdf", "application/pdf"},
                {".doc", "application/vnd.ms-word"},
                {".docx", "application/vnd.ms-word"},
                {".png", "image/png"},
                {".jpg", "image/jpeg"},
                {".rtf", "application/rtf" },
                {".zip", "application/zip" }
            };
        }

        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> UploadUserDocument(UserDocumentUploadViewModel model)
        {
            var success = await _documentService.SaveUserDocumentToFile(model.FormFile, model.UserId);
            if (success)
                return RedirectToAction(@"Details", "SystemUser", new { Id = model.UserId });
            else
                return RedirectToAction("Error", "Home");
        }

        [Authorize(Roles = "Teacher")]
        [HttpGet]
        public IActionResult UploadCourseDocument(string userId)
        {
            return View(new UserDocumentUploadViewModel { UserId = userId });
        }

        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> UploadCourseDocument(IFormFile formFile, string userId, int courseId)
        {
            var model = new CourseDocumentUploadViewModel
            {
                FormFile = formFile,
                UserId = userId,
                CourseId=courseId
            };

      
            var result = await _documentService.SaveCourseDocumentToFile(model);
            return RedirectToAction(@"Details", "Courses", new { Id = courseId });
        }

        // Should be accessible by everyone, but only from own documents unless teacher.
        [HttpGet]
        public async Task<IActionResult> RemoveDocument(int documentId, int entityId)
        {
            var document = await _documentService.GetDocumentByIdAsync(documentId);

            if (document == null)
                return NotFound();

            string adjustedPath = Path.GetDirectoryName(document.Path) + document.Name;

            var viewModel = new DocumentViewModel
            {
                EntityId = entityId,
                DocumentId = document.Id,
                ModelPath = adjustedPath,
                UploadDate = document.UploadTime
            };

            return View(viewModel);
        }

        // Should be accessible by everyone, but only from own documents unless teacher.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveDocument(DocumentViewModel viewModel)
        {
            await _documentService.RemoveDocument(viewModel);

            return RedirectToAction("Index", "Home");
        }
    }
}

Core/ViewComponents/Document/DocumentUploadViewComponent.cs
using LexiconLMS.Core.Services;
using LexiconLMS.Core.ViewModels;
using LexiconLMS.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace LexiconLMS.Core.ViewComponents.Document
{
    public class DocumentUploadViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;
        private readonly IUserService _userService;

        public DocumentUploadViewComponent(ApplicationDbContext applicationDbContext, IUserService userService)
        {
            _context = applicationDbContext;
            _userService = userService;
        }
        public async Task<IViewComponentResult> InvokeAsync(ClaimsPrincipal user, string entityId, string entityType)
        {
            var userId = _userService.GetUserId(user);

            switch (entityType)
            {
                case "Activity":
                    return ActivityDocumentUpload(userId, int.Parse(entityId));
                case "Course":
                    return CourseDocumentUpload(userId, int.Parse(entityId));
                case "Assignment":
                    return AssignmentDocumentUpload(userId, int.Parse(entityId));
                case "Module":
                    return ModuleDocumentUpload(userId, int.Parse(entityId));
                default:
                    break;
            }

            if (!entityId.Equals(_userService.GetUserId(user)))
            { 
                return View();
            }

            return View("User", new UserDocumentUploadViewModel { UserId = userId });
        }

        private IViewComponentResult ActivityDocumentUpload(string userId, int entityId)
        {
            return View("Activity", new ActivityDocumentUploadViewModel { ActivityId = entityId, UserId = userId });

        }


        private IViewComponentResult CourseDocumentUpload(string userId, int entityId)
        {
            return View("Course", new CourseDocumentUploadViewModel { CourseId = entityId, UserId = userId });
        }
        private IViewComponentResult AssignmentDocumentUpload(string userId, int entityId)
        {
            return View("Assignment", new AssignmentDocumentUploadViewModel { ActivityId = entityId, UserId = userId });
        }

        private IViewComponentResult ModuleDocumentUpload(string userId, int entityId)
        {
            return View("Module", new ModuleDocumentUploadViewModel { ModuleId = entityId, UserId = userId });
        }
    }
}

Core/ViewComponents/SystemUser/GetUsersNotInCourseViewComponent.cs
using LexiconLMS.Core.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LexiconLMS.Core.ViewComponents.SystemUser
{
    public class GetUsersNotInCourseViewComponent : ViewComponent
    {
        private readonly IUserService _userService;

        public GetUsersNotInCourseViewComponent(IUserService userService)
        {
            _userService = userService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int courseId, bool mainPage)
        {
            if (mainPage)
            {
                return View(await _userService.GetSystemUsersNotInCourse(courseId));

            }
            return View("StandardEdit", await _userService.GetSystemUsersNotInCourse(courseId));
        }
    }
}

Views/SystemUser/Delete.cshtml
@model LexiconLMS.Core.Models.SystemUser

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this user?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/SystemUser/Details.cshtml
@model LexiconLMS.Core.ViewModels.SystemUserDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SystemUser.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SystemUser.Name)
        </dd>
    </dl>
</div>
<div>
    @foreach (var document in Model.SystemUser.Documents)
    {
        <span>@document.Name</span>
        <a asp-action="DownloadDocument" asp-controller="Document" asp-route-documentId="@document.Id">Download</a> <text>|</text>
        <a asp-controller="Document" asp-action="RemoveDocument" asp-route-documentId="@document.Id" asp-route-entityId="@int.Parse("0")">Remove</a><br />
    }
</div>
<div>
    @await Component.InvokeAsync("DocumentUpload", new { entityId = Model.SystemUser.Id.ToString(), user = User, entityType = "" })
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.SystemUser.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/SystemUser/Edit.cshtml
@model LexiconLMS.Core.Models.SystemUser

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4" id="form">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group"><!--But how do we change the display name of this?-->
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="UploadUserDocument" asp-controller="Document" asp-route-userId="@Model.Id">Click here to upload a document</a>.
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/SystemUser/Index.cshtml
@model IEnumerable<LexiconLMS.Core.ViewModels.SystemUserViewModel>
@{
    ViewData["Title"] = "Users";
}
    <div id="mainbackgroundcolor" class="rounded-lg">
        <h1 class="rounded-top p-3" id="searchindex">@ViewData["Title"]</h1>

        <form class="text-light" asp-action="Filter"
              data-ajax="true"
              data-ajax-method="GET"
              data-ajax-mode="replace"
              data-ajax-update="usersupdate">
            <div class="input-group m-auto" id="searchindex">
                <input type="text" name="userName" class="form-control" placeholder="Search Student Name" />
                <div class="input-group-append">
                    <button type="submit" class="btn btn-primary "><i class="fa fa-search">&emsp;Search</i></button>
                </div>
            </div>
        </form>

        @if (User.IsInRole("Teacher"))
        {
            <div class="container pb-1">
                <a asp-area="Identity" asp-page="/Account/Register">Register</a>
            </div>
        }

        <div style="height: 55vh; overflow:auto;">
            <table class="table" id="mainbackgroundcolor">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                        <th>@Html.DisplayNameFor(model => model.Email)</th>
                        <th>@Html.DisplayNameFor(model => model.PhoneNumber)</th>
                        <th>Options</th>
                    </tr>
                </thead>
                <tbody id="usersupdate">
                    @await Html.PartialAsync("_SystemUsersPartial", Model)
                </tbody>
            </table>
        </div>
    </div>

Views/SystemUser/Register.cshtml
@model LexiconLMS.Core.Models.SystemUser

@{
    ViewData["Title"] = "Register new user";
}

<h1>Create</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}